### ISSUE TITLE
How do you set the transparent brackgound? 

### ISSUE THREAD

**Issue by sebalfaro** [Koalhack/koalight.nvim#2]
Hi there, i wanted to set the background and use the transparent one that you have in this image, how do you do that? Thanks!!

![image](https://github.com/Koalhack/koalight.nvim/assets/89085542/1cc76bf2-c635-4cc1-8361-2d0fa211fe0a)

**Comment by Koalhack** [comment]
Hello, I'll be glad to help you.

1. First of all, you need to use a terminal emulator that supports transparent background (Windows Terminal, iTerm, Warp, etc...) and configure it to be transparent/translucent.
2. Secondly, my koalight.nvim theme doesn't support transparency at the moment, so you'll need to use the [transparent.nvim](https://github.com/xiyaowong/transparent.nvim) plugin or you can try this snippet `vim.api.nvim_set_hl(0, 'Normal', { bg = 'none' })`.

I hope this helps, if you have any further problems please don't hesitate to open a question.
Best regards

**Comment by Koalhack** [comment]
Here is my configuration file for the [transparent.nvim](https://github.com/xiyaowong/transparent.nvim) plugin

```lua
local M = {
  'xiyaowong/nvim-transparent'
}

function M.config()
  local status, transparent = pcall(require, 'transparent')
  if (not status) then return end

  transparent.setup({
    extra_groups = { -- table/string: additional groups that should be cleared

      --telescope.nvim
      "FloatBorder",
      "TelescopeNormal",

      --Cmp.nvim
      "Pmenu",
      "Float",
      "NormalFloat",

      -- nvim-bufferline.lua
      "BufferLineFill",
      "BufferLineBackground",
    },
    exclude_groups = {}, -- table: groups you don't want to clear
  })
end

return M
```

**Comment by sebalfaro** [comment]
> Here is my configuration file for the [transparent.nvim](https://github.com/xiyaowong/transparent.nvim) plugin
> 
> ```lua
> local M = {
>   'xiyaowong/nvim-transparent'
> }
> 
> function M.config()
>   local status, transparent = pcall(require, 'transparent')
>   if (not status) then return end
> 
>   transparent.setup({
>     extra_groups = { -- table/string: additional groups that should be cleared
> 
>       --telescope.nvim
>       "FloatBorder",
>       "TelescopeNormal",
> 
>       --Cmp.nvim
>       "Pmenu",
>       "Float",
>       "NormalFloat",
> 
>       -- nvim-bufferline.lua
>       "BufferLineFill",
>       "BufferLineBackground",
>     },
>     exclude_groups = {}, -- table: groups you don't want to clear
>   })
> end
> 
> return M
> ```

Working on my end, thank you!!
